"""label

Revision ID: 42f2f896009e
Revises: 5699ad3681c1
Create Date: 2024-09-01 23:34:25.369911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42f2f896009e'
down_revision: Union[str, None] = '5699ad3681c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mp_label_ozon_review_media',
    sa.Column('review_media_id', sa.String(length=32), nullable=False, comment='PK - Ozon review media ID'),
    sa.Column('label', sa.Integer(), nullable=True, comment='Ozon review media label'),
    sa.ForeignKeyConstraint(['review_media_id'], ['mp_ozon_review_media.id'], ),
    sa.PrimaryKeyConstraint('review_media_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mp_label_ozon_review_media')
    # ### end Alembic commands ###
