"""parser

Revision ID: 5699ad3681c1
Revises: d4a2929a3493
Create Date: 2024-09-01 23:14:01.742777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5699ad3681c1'
down_revision: Union[str, None] = 'd4a2929a3493'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mp_parser_ozon_category_meta',
    sa.Column('category_id', sa.Integer(), nullable=False, comment='PK - Ozon category ID'),
    sa.Column('parsing_priority', sa.Integer(), nullable=False, comment='Parsing priority - less first in a queue'),
    sa.Column('is_parsing_enabled', sa.Boolean(), nullable=False, comment='Wheather to parse category'),
    sa.ForeignKeyConstraint(['category_id'], ['mp_ozon_category.id'], ),
    sa.PrimaryKeyConstraint('category_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mp_parser_ozon_category_meta')
    # ### end Alembic commands ###
