"""add tg post

Revision ID: a62a2a47baa0
Revises: 42f2f896009e
Create Date: 2024-09-12 01:11:05.535003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a62a2a47baa0'
down_revision: Union[str, None] = '42f2f896009e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mp_tg_ozon_post',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='PK - post ID.'),
    sa.Column('review_uuid', sa.String(length=36), nullable=False, comment='PK - Ozon review media ID'),
    sa.Column('admin_comment', sa.Text(), nullable=True, comment='Channel admin comment'),
    sa.Column('post_at', sa.DateTime(), nullable=True, comment='Datetime when to make a post.'),
    sa.Column('posted_at', sa.DateTime(), nullable=True, comment='Posted in the channel datetime.'),
    sa.Column('is_valid', sa.Boolean(), nullable=True, comment='Flag - is valid to post.'),
    sa.ForeignKeyConstraint(['review_uuid'], ['mp_ozon_review.uuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mp_tg_ozon_post')
    # ### end Alembic commands ###
