"""content marks

Revision ID: 3854c637aa4f
Revises: b949e5da0ac2
Create Date: 2024-09-29 00:25:38.949687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3854c637aa4f'
down_revision: Union[str, None] = 'b949e5da0ac2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mp_post_ozon_review_media',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='PK of the relation'),
    sa.Column('post_id', sa.Integer(), nullable=True, comment='FK on post ID'),
    sa.Column('review_media_id', sa.String(length=32), nullable=False, comment='FK on review media ID'),
    sa.Column('is_decliend', sa.Boolean(), nullable=False, comment='Review media decliend for post on the moderation'),
    sa.ForeignKeyConstraint(['post_id'], ['mp_post.id'], ),
    sa.ForeignKeyConstraint(['review_media_id'], ['mp_ozon_review_media.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('mp_post', sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Additional data'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mp_post', 'data')
    op.drop_table('mp_post_ozon_review_media')
    # ### end Alembic commands ###
