"""delete old post

Revision ID: 0dbad072f4fd
Revises: 3854c637aa4f
Create Date: 2024-09-29 01:01:48.787063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0dbad072f4fd'
down_revision: Union[str, None] = '3854c637aa4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mp_tg_ozon_post')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mp_tg_ozon_post',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False, comment='PK - post ID.'),
    sa.Column('review_uuid', sa.VARCHAR(length=36), autoincrement=False, nullable=False, comment='PK - Ozon review media ID'),
    sa.Column('admin_comment', sa.TEXT(), autoincrement=False, nullable=True, comment='Channel admin comment'),
    sa.Column('post_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True, comment='Datetime when to make a post.'),
    sa.Column('posted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True, comment='Posted in the channel datetime.'),
    sa.Column('is_valid', sa.BOOLEAN(), autoincrement=False, nullable=True, comment='Flag - is valid to post.'),
    sa.ForeignKeyConstraint(['review_uuid'], ['mp_ozon_review.uuid'], name='mp_tg_ozon_post_review_uuid_fkey'),
    sa.PrimaryKeyConstraint('id', name='mp_tg_ozon_post_pkey')
    )
    # ### end Alembic commands ###
