"""channel, scheduler

Revision ID: e195e9c4cc64
Revises: 0dbad072f4fd
Create Date: 2024-09-29 12:14:37.834665

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'e195e9c4cc64'
down_revision: Union[str, None] = '0dbad072f4fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mp_channel',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Channel ID'),
    sa.Column('name', sa.String(length=128), nullable=False, comment='Name of the channel'),
    sa.Column('description', sa.Text(), nullable=True, comment='Description of the channel'),
    sa.Column('chat_id', sa.String(length=32), nullable=False, comment='Telegram chat id for bot posting'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mp_post_scheduler_trigger',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Trigger ID'),
    sa.Column('name', sa.String(length=128), nullable=False, comment='Name of the trigger'),
    sa.Column('channel_id', sa.Integer(), nullable=False, comment='Foreign key to Channel'),
    sa.Column('post_type_id', sa.Integer(), nullable=False, comment='Foreign key to PostType'),
    sa.Column('post_pool_id', sa.Integer(), nullable=False, comment='Foreign key to PostPool'),
    sa.Column('time', sa.Time(), nullable=False, comment='Time of day to run the trigger'),
    sa.Column('weekdays', postgresql.ARRAY(sa.Enum('Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun', name='weekday_enum')), nullable=False, comment='Weekdays to run the job (array of weekdays)'),
    sa.ForeignKeyConstraint(['channel_id'], ['mp_channel.id'], ),
    sa.ForeignKeyConstraint(['post_pool_id'], ['mp_post_pool.id'], ),
    sa.ForeignKeyConstraint(['post_type_id'], ['mp_post_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mp_post_scheduler_trigger')
    op.drop_table('mp_channel')
    op.execute('DROP TYPE IF EXISTS weekday_enum;')
    # ### end Alembic commands ###
