"""ozon, scraper

Revision ID: 5cadcea5aec6
Revises: 
Create Date: 2024-10-06 00:15:02.541506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cadcea5aec6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mc_ozon_category',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Category ID from Ozon - PK'),
    sa.Column('parent_id', sa.Integer(), nullable=True, comment='Parent category ID from Ozon'),
    sa.Column('level', sa.Integer(), nullable=False, comment='Category level in the category tree'),
    sa.Column('url', sa.String(length=2083), nullable=False, comment='URL to the category page'),
    sa.Column('short_url', sa.String(length=2083), nullable=False, comment='Short URL to the category page'),
    sa.Column('name', sa.String(length=1024), nullable=True, comment='Category name'),
    sa.Column('image_url', sa.String(length=2083), nullable=True, comment='URL to the category image'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mc_ozon_product',
    sa.Column('sku_id', sa.BigInteger(), nullable=False, comment='Stock Keeping Unit ID'),
    sa.Column('name', sa.String(length=1024), nullable=True, comment='Product name'),
    sa.Column('price', sa.Integer(), nullable=True, comment='Current price of the product in RUB'),
    sa.Column('original_price', sa.Integer(), nullable=True, comment='Original price of the product before discount in RUB'),
    sa.Column('stock', sa.Integer(), nullable=True, comment='Stock availability'),
    sa.Column('rating', sa.Float(), nullable=True, comment='Average rating of the product'),
    sa.Column('review_count', sa.Integer(), nullable=True, comment='Number of reviews for the product'),
    sa.Column('url', sa.String(length=2083), nullable=False, comment='URL to the product page'),
    sa.Column('image_url', sa.String(length=2083), nullable=True, comment='URL to the product image'),
    sa.Column('category_id', sa.Integer(), nullable=True, comment='Product category ID'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Timestamp of record creation'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Timestamp of last record update'),
    sa.ForeignKeyConstraint(['category_id'], ['mc_ozon_category.id'], ),
    sa.PrimaryKeyConstraint('sku_id')
    )
    op.create_table('mc_scraper_ozon_category_meta',
    sa.Column('category_id', sa.Integer(), nullable=False, comment='PK - Ozon category ID'),
    sa.Column('parsing_priority', sa.Integer(), nullable=False, comment='Parsing priority - less first in a queue'),
    sa.Column('is_parsing_enabled', sa.Boolean(), nullable=False, comment='Wheather to parse category'),
    sa.ForeignKeyConstraint(['category_id'], ['mc_ozon_category.id'], ),
    sa.PrimaryKeyConstraint('category_id')
    )
    op.create_table('mc_ozon_review',
    sa.Column('uuid', sa.String(length=36), nullable=False, comment='Unique identifier for the review'),
    sa.Column('product_sku_id', sa.BigInteger(), nullable=True, comment='Product Stock Keeping Unit ID'),
    sa.Column('rating', sa.Integer(), nullable=True, comment='Rating given by the reviewer'),
    sa.Column('user_name', sa.String(length=64), nullable=True, comment='Name of the user who reviewed'),
    sa.Column('user_image_url', sa.String(length=2083), nullable=True, comment="URL to the user's profile image"),
    sa.Column('comment_count', sa.Integer(), nullable=False, comment='Number of comments on the review'),
    sa.Column('url', sa.String(length=2083), nullable=False, comment='URL to the review page'),
    sa.Column('like_count', sa.Integer(), nullable=True, comment='Number of likes on the review'),
    sa.Column('dislike_count', sa.Integer(), nullable=True, comment='Number of dislikes on the review'),
    sa.Column('comment_text', sa.Text(), nullable=True, comment='Text of the review'),
    sa.Column('advantages_text', sa.Text(), nullable=True, comment='Text describing the advantages in the review'),
    sa.Column('disadvantages_text', sa.Text(), nullable=True, comment='Text describing the disadvantages in the review'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Timestamp of record creation'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Timestamp of last record update'),
    sa.ForeignKeyConstraint(['product_sku_id'], ['mc_ozon_product.sku_id'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('mc_ozon_review_media',
    sa.Column('id', sa.String(length=32), nullable=False, comment='Product Media ID - PK (md5 from id from media URL)'),
    sa.Column('review_uuid', sa.String(length=36), nullable=False, comment='Foreign Key to Ozon review'),
    sa.Column('type', sa.Enum('video', 'image', name='ozon_media_type'), nullable=False, comment='Type of media (video or image)'),
    sa.Column('url', sa.String(length=2083), nullable=False, comment='URL to the media resource'),
    sa.Column('extension', sa.String(length=16), nullable=False, comment='File extension of the media (without dot).'),
    sa.Column('video_duration_sec', sa.Integer(), nullable=True, comment='Video duration in seconds'),
    sa.Column('width', sa.Integer(), nullable=True, comment='Media width pixels'),
    sa.Column('height', sa.Integer(), nullable=True, comment='Media height pixels'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Timestamp of record creation'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Timestamp of last record update'),
    sa.ForeignKeyConstraint(['review_uuid'], ['mc_ozon_review.uuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mc_ozon_review_media')
    op.drop_table('mc_ozon_review')
    op.drop_table('mc_scraper_ozon_category_meta')
    op.drop_table('mc_ozon_product')
    op.drop_table('mc_ozon_category')
    op.execute('DROP TYPE IF EXISTS ozon_media_type;')
    # ### end Alembic commands ###
