services:

  parser_db:
    image: postgres:14
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: unless-stopped
    ports:
      - 5530:5432
    volumes:
      - parser_db:/var/lib/postgresql/data

  moderation_bot:
    image: moderation-bot
    build:
      context: ../../
      dockerfile: contrib/docker/moderation_bot/Dockerfile
    environment: &app_envs
      DATABASE_URL: ${DATABASE_URL}
      TELEGRAM_API_TOKEN: ${TELEGRAM_API_TOKEN}

  cron:
    image: mp-cron
    build:
      context: ../../
      dockerfile: contrib/docker/cron/Dockerfile
    environment:
      <<: *app_envs
      TELEGRAM_CHANNEL_CHAT_ID: ${TELEGRAM_CHANNEL_CHAT_ID}

volumes:
  parser_db:
