services:

  parser_db:
    image: postgres:14
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: unless-stopped
    ports:
      - 5530:5432
    volumes:
      - parser_db:/var/lib/postgresql/data

  labling_bot:
    image: labling-bot
    build:
      context: ../../
      dockerfile: contrib/docker/labling_bot/Dockerfile
    environment:
      DATABASE_URL: ${DATABASE_URL}
      TELEGRAM_API_TOKEN: ${TELEGRAM_API_TOKEN}

volumes:
  parser_db:
