services:

  parser_db:
    image: postgres:14
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - parser_db:/var/lib/postgresql/data

  cron:
    image: mp-cron
    build:
      context: ../../
      dockerfile: contrib/docker/cron/Dockerfile
    profiles:
      - depricated

volumes:
  parser_db:
