# docker compose --env-file=.env up -d
services:

  parser_db:
    image: postgres:14
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: unless-stopped
    ports:
      - 5530:5432
    volumes:
      - parser_db:/var/lib/postgresql/data
    networks:
      - common-net

volumes:
  parser_db:

networks:
  common-net:
    name: common-net
